language: php

branches:
  except:
    - 1.3

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=2.2.9
  - CAKE_VERSION=master

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - mv ../CakePHP-TALTAL plugins/Taltal
  - chmod -R 777 ../cakephp/app/tmp
  - echo "
    CakePlugin::loadAll();
    " >> ../cakephp/app/Config/bootstrap.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test Taltal View/PhptalView --stderr
